### ISSUE TITLE
Tags and Category Page - layout isn't in line with the rest

### ISSUE THREAD

**Issue by geisslet** [sapcc/hugo-documentation-templater#19]
sample: https://documentation.global.cloud.sap/tags/api/

**Comment by ArtieReus** [comment]
Hi! this is the official template for tags in docsy
https://www.docsy.dev/tags/labelling/

**Comment by geisslet** [comment]
yeah, but your link looks nicer than ours - sample: https://documentation.global.cloud.sap/categories/billing/ (looks squished)

@I870640

**Comment by ArtieReus** [comment]
@geisslet, the version of the templater used here is 1.5.0, which lags behind the latest 1.6.5 version. I've tested locally with the most recent version, and everything appears to be fine. Please consider upgrading the templater and do some testing.
