### ISSUE TITLE
"Default landing page content" is hardcoded

### ISSUE THREAD

**Issue by geisslet** [sapcc/hugo-documentation-templater#4]
https://github.com/sapcc/hugo-documentation-templater/blob/dc8192eeef7b967990550e1786d4bbd3f9391596/layouts/partials/landing-page-content-default.html#L3

.. so if you set hero-title and hero-subtitle it's still shown which makes the usage of default landing page not useful - needs also a variable

**Comment by ArtieReus** [comment]
fixed! Thx!!
